version: '3'

services:
  ansible:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/ansible
    command: ansible-playbook Nginx_MongoDB_play.yml
                                                
