---
- name: Install Nginx and MongoDB
  hosts: localhost
  become: true
  
  roles:
    - InstallNginx
    - InstallMongoDB

  handlers:
    - name: start mongodb
      service: 
        name: mongod 
        state: started

